# Generated by Django 4.2.16 on 2024-09-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=510)),
                ('price', models.FloatField()),
                ('image', models.CharField(max_length=1024)),
            ],
        ),
    ]
